name: Install Dependencies
description: Installs all project dependencies.
inputs:
  npm-token:
    description: Needed for authenticating with GitHub's package repository.
    required: true
runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      uses: asdf-vm/actions/install@v2
    - name: Hydrate node modules cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Configure npmrc
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" >> .npmrc
        echo "registry=https://registry.npmjs.org" >> .npmrc
        echo "always-auth=true" >> .npmrc
    - name: Install node modules
      shell: bash
      run: yarn install --frozen-lockfile
