name: "PR Test"

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  pr-test:
    name: "PR Test"
    runs-on: "ubuntu-latest"
    environment: integration-sandbox

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
        env:
          SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
