name: "PR Test"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  pr-test:
    name: "PR Test"
    runs-on: "ubuntu-latest"
    environment: integration-sandbox

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command          
      - run: npm test
        env:
          SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
